export const projects = [
  {
    id: "1",
    name: "Portfolio Hub",
    description:
      "A central hub to showcase your portfolio projects with details and links.",
    tags: ["React", "Node.js", "CSS"],
    github_link: "https://github.com/yourusername/portfolio-hub",
  },
  {
    id: "2",
    name: "Task Tracker",
    description: "A web app to track and manage your daily tasks efficiently.",
    tags: ["Vue.js", "Firebase", "Tailwind CSS"],
    github_link: "https://github.com/yourusername/task-tracker",
  },
  {
    id: "3",
    name: "Recipe Vault",
    description: "A place to store and organize all your favorite recipes.",
    tags: ["Angular", "Node.js", "Bootstrap"],
    github_link: "https://github.com/yourusername/recipe-vault",
  },
  {
    id: "4",
    name: "Weather Watch",
    description:
      "Get real-time weather updates for any location around the world.",
    tags: ["React", "OpenWeather API", "Sass"],
    github_link: "https://github.com/yourusername/weather-watch",
  },
  {
    id: "5",
    name: "Blog Base",
    description: "A simple blogging platform to share your thoughts and ideas.",
    tags: ["Gatsby", "GraphQL", "Styled Components"],
    github_link: "https://github.com/yourusername/blog-base",
  },
];

export const tags = [
  "nextjs",
  "reactjs",
  "vanillajs",
  "nodejs",
  "expressjs",
  "laravel",
  "django",
  "java",
  "python",
  "tailwindcss",
  "typescript",
  "webpack",
  "git",
  "sql",
  "php",
  "mysql",
  "css",
  "seo",
  "responsive-web-design",
  "json",
  "oop",
  "postgresql",
  "rest-api",
  "javascript",
  "html",
  "css",
];
